### ISSUE TITLE
Problema construyendo la imagen de Docker en Powershell

### ISSUE THREAD

**Issue by yerkozec** [OfriSoftware/Grupo-1#1]
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Composer could not find a composer.json file in /app
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
The command '/bin/sh -c composer install' returned a non-zero code: 1

no se encuentra el archivo composer.json

**Comment by danieldiazastudillo** [comment]
Pasos de reproducción de error...¿?...
